name: cantwait28
description: A Flutter project that counts days down to exciting dates in the future.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.13.3

  firebase_core: ^2.24.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  firebase_ui_auth: ^1.11.0
  intl: ^0.19.0
  firebase_auth: ^4.15.0
  bloc: ^8.1.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
